spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/stack_over_flow
    username: root
    password: shakee2001
  flyway:
    baseline-on-migrate: true
